const CACHE_NAME = "voicer-pwa-v71";
const APP_SHELL = [
	"./",
	"./index.html",
	"./style.css",
	"./garsai/noriu.mp3",
	"./garsai/eiti.mp3",
	"./garsai/padėk.mp3",
	"./garsai/taip.mp3",
	"./garsai/ne.mp3",
	"./garsai/emocijų garsai/įsimylėjęs.mp3",
	"./garsai/emocijų garsai/VERKIU.mp3",
	"./garsai/emocijų garsai/ramybė.mp3",
	"./garsai/emocijų garsai/piktas.mp3",
	"./garsai/emocijų garsai/pavargęs.mp3",
	"./garsai/emocijų garsai/patinka.mp3",
	"./garsai/emocijų garsai/panika.mp3",
	"./garsai/emocijų garsai/nuobodu.mp3",
	"./garsai/emocijų garsai/nerimas.mp3",
	"./garsai/emocijų garsai/LIŪDNA.mp3",
	"./garsai/emocijų garsai/laimė.mp3",
	"./garsai/emocijų garsai/irzlus.mp3",
	"./garsai/patiekalų garsai/virti kiaušiniai.mp3",
	"./garsai/patiekalų garsai/sriuba.mp3",
	"./garsai/patiekalų garsai/spagečiai.mp3",
	"./garsai/patiekalų garsai/salotos.mp3",
	"./garsai/patiekalų garsai/pica.mp3",
	"./garsai/patiekalų garsai/omletas.mp3",
	"./garsai/patiekalų garsai/maltinukas.mp3",
	"./garsai/patiekalų garsai/lietiniai.mp3",
	"./garsai/patiekalų garsai/lazanija.mp3",
	"./garsai/patiekalų garsai/kepti kiaušiniai.mp3",
	"./garsai/patiekalų garsai/kepsnys.mp3",
	"./garsai/patiekalų garsai/dešrelės.mp3",
	"./garsai/patiekalų garsai/burgeris.mp3",
	"./garsai/patiekalų garsai/blynai.mp3",
	"./garsai/kepiniai garsai/bandelė.mp3",
	"./garsai/kepiniai garsai/duonelė.mp3",
	"./garsai/kepiniai garsai/dešrainių bandelė.mp3",
	"./garsai/kepiniai garsai/mėsainių bandelė.mp3",
	"./garsai/kepiniai garsai/ilgas batonas.mp3",
	"./garsai/kepiniai garsai/juoda duona.mp3",
	"./garsai/kepiniai garsai/keksiukas.mp3",
	"./garsai/kepiniai garsai/kruasanas.mp3",
	"./garsai/kepiniai garsai/sumuštinių duona.mp3",
	"./garsai/kepiniai garsai/tortas.mp3",
	"./garsai/užkandžų garsai/trapučiai.mp3",
	"./garsai/užkandžų garsai/riešutai.mp3",
	"./garsai/užkandžų garsai/džiovinti vaisiai.mp3",
	"./garsai/užkandžų garsai/popkornai.mp3",
	"./garsai/užkandžų garsai/traškučiai.mp3",
	"./garsai/užkandžų garsai/lazdelės.mp3",
	"./garsai/saldumynai garsai/bandelė.mp3",
	"./garsai/saldumynai garsai/guminukai.mp3",
	"./garsai/saldumynai garsai/ledai.mp3",
	"./garsai/saldumynai garsai/saldainis.mp3",
	"./garsai/saldumynai garsai/sausainis.mp3",
	"./garsai/saldumynai garsai/vaflis.mp3",
	"./garsai/saldumynai garsai/čiulpinukas.mp3",
	"./garsai/saldumynai garsai/šokoladas.mp3",
	"./garsai/gerti garsai/vanduo.mp3",
	"./garsai/gerti garsai/sultys.mp3",
	"./garsai/gerti garsai/vanduo su citrina.mp3",
	"./garsai/gerti garsai/gazuotas vanduo.mp3",
	"./garsai/gerti garsai/limonadas.mp3",
	"./garsai/gerti garsai/kokteilis.mp3",
	"./garsai/gerti garsai/kava.mp3",
	"./garsai/gerti garsai/arbata.mp3",
	"./garsai/gerti garsai/kakava.mp3",
	"./garsai/gerti garsai/pienas.mp3",
	"./garsai/tualetas garsai/nuleisti vandenį.mp3",
	"./garsai/tualetas garsai/oro gaiviklis.mp3",
	"./garsai/tualetas garsai/plauti rankas.mp3",
	"./garsai/tualetas garsai/rankšluostis.mp3",
	"./garsai/tualetas garsai/skystas muilas.mp3",
	"./garsai/tualetas garsai/tualetas.mp3",
	"./garsai/tualetas garsai/tualetinis popierius.mp3",
	"./garsai/tualetas garsai/tualeto šepetys.mp3",
	"./garsai/bendraukime/apsikabinkim.mp3",
	"./garsai/bendraukime/atsiprašau.mp3",
	"./garsai/bendraukime/ačiū.mp3",
	"./garsai/bendraukime/labas.mp3",
	"./garsai/bendraukime/ne.mp3",
	"./garsai/bendraukime/stop.mp3",
	"./garsai/bendraukime/taip.mp3",
	"./garsai/bendraukime/viso gero.mp3",
	"./garsai/skauda/ausis.mp3",
	"./garsai/skauda/dantys.mp3",
	"./garsai/skauda/galva.mp3",
	"./garsai/skauda/gerklė.mp3",
	"./garsai/skauda/koja.mp3",
	"./garsai/skauda/nugara.mp3",
	"./garsai/skauda/pilvas.mp3",
	"./garsai/skauda/ranka.mp3",
	"./garsai/namų ruoša/išnešti šiukšles.mp3",
	"./garsai/namų ruoša/laistyti.mp3",
	"./garsai/namų ruoša/laistyti gėles.mp3",
	"./garsai/namų ruoša/plauti grindis.mp3",
	"./garsai/namų ruoša/plauti indus.mp3",
	"./garsai/namų ruoša/siurbti.mp3",
	"./garsai/namų ruoša/skalbti.mp3",
	"./garsai/namų ruoša/džiovinti.mp3",
	"./garsai/namų ruoša/valyti dulkes.mp3",
	"./garsai/poilsis/ausinės.mp3",
	"./garsai/poilsis/kvėpavimas.mp3",
	"./garsai/poilsis/miegas.mp3",
	"./garsai/poilsis/sėdmaišis.mp3",
	"./garsai/pramogos/piešimas.mp3",
	"./garsai/pramogos/žaisti.mp3",
	"./garsai/pramogos/kompiuteris.mp3",
	"./garsai/pramogos/televizorius.mp3",
	"./garsai/pramogos/koncertas.mp3",
	"./garsai/pramogos/žaidimai.mp3",
	"./garsai/pramogos/teatras.mp3",
	"./garsai/pramogos/piknikas.mp3",
	"./garsai/viešos erdvės/mokykla.mp3",
	"./garsai/viešos erdvės/darželis.mp3",
	"./garsai/viešos erdvės/parduotuvė.mp3",
	"./garsai/viešos erdvės/ligoninė.mp3",
	"./garsai/viešos erdvės/dantistas.mp3",
	"./garsai/viešos erdvės/kirpykla.mp3",
	"./garsai/viešos erdvės/kavinė.mp3",
	"./garsai/viešos erdvės/biblioteka.mp3",
	"./garsai/gamta/parkas.mp3",
	"./garsai/gamta/žaidimų aikštelė.mp3",
	"./garsai/gamta/jūra.mp3",
	"./garsai/gamta/ežeras.mp3",
	"./garsai/gamta/upė.mp3",
	"./garsai/gamta/miškas.mp3",
	"./garsai/vaisiai/obuolys.mp3",
	"./garsai/vaisiai/kriaušė.mp3",
	"./garsai/vaisiai/bananas.mp3",
	"./garsai/vaisiai/apelsinas.mp3",
	"./garsai/vaisiai/mandarinas.mp3",
	"./garsai/vaisiai/laimas.mp3",
	"./garsai/vaisiai/greipfrutas.mp3",
	"./garsai/vaisiai/citrina.mp3",
	"./garsai/vaisiai/pamelo.mp3",
	"./garsai/vaisiai/melionas.mp3",
	"./garsai/vaisiai/arbūzas.mp3",
	"./garsai/vaisiai/slyva.mp3",
	"./garsai/vaisiai/avokadas.mp3",
	"./garsai/vaisiai/kivis.mp3",
	"./garsai/vaisiai/mangas.mp3",
	"./garsai/vaisiai/ananasas.mp3",
	"./garsai/vaisiai/granatas.mp3",
	"./garsai/vaisiai/persimonas.mp3",
	"./garsai/kiaušiniai/kiaušiniai.mp3",
	"./garsai/kiaušiniai/putpelių kiaušiniai.mp3",
	"./garsai/pienas/jogurtas.mp3",
	"./garsai/pienas/grietinė.mp3",
	"./garsai/pienas/užtepėlė.mp3",
	"./garsai/pienas/pienas.mp3",
	"./garsai/pienas/krietinėlė.mp3",
	"./garsai/pienas/sviestas.mp3",
	"./garsai/pienas/sūris.mp3",
	"./garsai/pienas/varškė.mp3",
	"./garsai/mėsa/šoninė.mp3",
	"./garsai/mėsa/jautiena.mp3",
	"./garsai/mėsa/malta mėsa.mp3",
	"./garsai/mėsa/blauzdelės.mp3",
	"./garsai/mėsa/šonkauliukai.mp3",
	"./garsai/mėsa/šviežios dešrelės.mp3",
	"./garsai/mėsa/vištienos krutinėlė.mp3",
	"./garsai/mėsa/vištienos petukai.mp3",
	"./garsai/daržovės/bulvė.mp3",
	"./garsai/daržovės/saldi bulvė.mp3",
	"./garsai/daržovės/morka.mp3",
	"./garsai/daržovės/burokėlis.mp3",
	"./garsai/daržovės/ridikėlis.mp3",
	"./garsai/daržovės/česnakas.mp3",
	"./garsai/daržovės/svogūnas.mp3",
	"./garsai/daržovės/pomidoras.mp3",
	"./garsai/daržovės/agurkas.mp3",
	"./garsai/daržovės/salotos.mp3",
	"./garsai/daržovės/paprika.mp3",
	"./garsai/daržovės/cukinija.mp3",
	"./garsai/daržovės/moliugas.mp3",
	"./garsai/daržovės/kopūstas.mp3",
	"./garsai/daržovės/brokolis.mp3",
	"./garsai/daržovės/žiedinis kopūstas.mp3",
	"./garsai/daržovės/žirniai.mp3",
	"./garsai/daržovės/kukurūzai.mp3",
	"./garsai/uogos/vyšnia.mp3",
	"./garsai/uogos/žemuogė.mp3",
	"./garsai/uogos/braškė.mp3",
	"./garsai/uogos/avietė.mp3",
	"./garsai/uogos/šilauogė.mp3",
	"./garsai/uogos/vynuogė.mp3",
	"./garsai/transportas/dviratis.mp3",
	"./garsai/transportas/paspirtukas.mp3",
	"./garsai/transportas/automobilis.mp3",
	"./garsai/transportas/autobusas.mp3",
	"./garsai/transportas/traukinys.mp3",
	"./garsai/transportas/lėktuvas.mp3",
	"./garsai/transportas/laivas.mp3",
	"./garsai/namai/svetainė.mp3",
	"./garsai/namai/miegamasis.mp3",
	"./garsai/namai/vonia.mp3",
	"./garsai/namai/virtuvė.mp3",
	"./garsai/namai/koridorius.mp3",
	"./garsai/namai/drabužinė.mp3",
	"./ikonos/NORIU.svg",
	"./ikonos/padėk.svg",
	"./ikonos/taip.svg",
	"./ikonos/ne.svg",
	"./ikonos/eiti.svg",
	"./ikonos/Car.svg",
	"./ikonos/valgyti.svg",
	"./ikonos/gerti.svg",
	"./ikonos/Plus.svg",
	"./kategoriju-ikonos/EMOCIJOS.svg",
	"./kategoriju-ikonos/VALGYTI.svg",
	"./kategoriju-ikonos/GERTI.svg",
	"./kategoriju-ikonos/TUALETAS.svg",
	"./kategoriju-ikonos/BENDRAUKIME.svg",
	"./kategoriju-ikonos/SKAUDA.svg",
	"./kategoriju-ikonos/VEIKLOS.svg",
	"./kategoriju-ikonos/VIETOS.svg",
	"./kategoriju-ikonos/TRANSPORTAS.svg",
	"./kategoriju-ikonos/GAMINTI.svg",
	"./kategoriju-ikonos/SPORTAS.svg",
	"./kategoriju-ikonos/DAIKTAI.svg",
	"./kategoriju-ikonos/LAIKAS.svg",
	"./kategoriju-ikonos/SKAIČIAI.svg",
	"./kategoriju-ikonos/SPALVOS.svg",
	"./IKONOS POGRUPIAI/PATIEKLAI.svg",
	"./IKONOS POGRUPIAI/KEPINIAI.svg",
	"./IKONOS POGRUPIAI/UŽKANDŽIAI.svg",
	"./IKONOS POGRUPIAI/SALDUMYNAI.svg",
	"./IKONOS POGRUPIAI/NAMŲ RUOŠA.svg",
	"./IKONOS POGRUPIAI/POILSIS.svg",
	"./IKONOS POGRUPIAI/PRAMOGOS.svg",
	"./IKONOS POGRUPIAI/NAMAI.svg",
	"./IKONOS POGRUPIAI/VIEŠOS ERDVĖS.svg",
	"./IKONOS POGRUPIAI/GAMTA.svg",
	"./IKONOS POGRUPIAI/MAISTO PRODUKTAI.svg",
	"./IKONOS POGRUPIAI/GAMINIMO PROCESAS.svg",
	"./IKONOS POGRUPIAI/INDAI.svg",
	"./IKONOS POGRUPIAI/VAISIAI.svg",
	"./IKONOS POGRUPIAI/UOGOS.svg",
	"./IKONOS POGRUPIAI/DARŽOVĖS.svg",
	"./IKONOS POGRUPIAI/DUONA.svg",
	"./IKONOS POGRUPIAI/KIAUŠINIAI.svg",
	"./IKONOS POGRUPIAI/PIENAS.svg",
	"./IKONOS POGRUPIAI/MĖSA.svg",
	"./IKONOS POGRUPIAI/ŽUVIS.svg",
	"./IKONOS POGRUPIAI/MAKARONAI.svg",
	"./IKONOS POGRUPIAI/PADAŽAI.svg",
	"./IKONOS POGRUPIAI/KRUOPOS.svg",
	"./IKONOS POGRUPIAI/PRIESKONIAI.svg",
	"./IKONOS POGRUPIAI/ASMENINIAI DAIKTAI.svg",
	"./IKONOS POGRUPIAI/APRANGA.svg",
	"./IKONOS POGRUPIAI/HIGIENA.svg",
	"./IKONOS POGRUPIAI/DEŠRELĖS.svg",
	"./NAVIGACIJOA IKONOS/emocijjos.svg",
	"./NAVIGACIJOA IKONOS/megstamiausi.svg",
	"./NAVIGACIJOA IKONOS/SpeakerSimpleHigh.svg"
];

self.addEventListener("install", (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME)
			.then((cache) => cache.addAll(APP_SHELL))
			.then(() => self.skipWaiting())
	);
});

self.addEventListener("activate", (event) => {
	event.waitUntil(
		caches.keys()
			.then((cacheNames) => Promise.all(
				cacheNames
					.filter((cacheName) => cacheName.startsWith("voicer-pwa-") && cacheName !== CACHE_NAME)
					.map((cacheName) => caches.delete(cacheName))
			))
			.then(() => self.clients.claim())
	);
});

self.addEventListener("fetch", (event) => {
	const requestUrl = new URL(event.request.url);
	if (event.request.method !== "GET" || requestUrl.origin !== self.location.origin) {
		return;
	}

	event.respondWith(
		caches.match(event.request).then((cachedResponse) => {
			if (cachedResponse) {
				return cachedResponse;
			}

			return fetch(event.request).catch(() => caches.match("./index.html"));
		})
	);
});
